In [116]:
import pandas as pd

In [117]:
df=pd.read_csv("clean_data.csv")

df.head(2)

,Status,Certificate ID,Certificate Holder,Scope,Raw Material,Add-Ons,Products,Valid From,Valid Until,Suspended,Issuing CB,Map,Certificate,Audit Report
0,valid.,EU-ISCC-Cert-PL230-01473001,"Bioenergo - Komplex, s.r.o., Kolín, Czech Rep...","FG, TRS, PU",Rapeseed / canola,NaN,Crude oil,2024-03-22,2025-03-21,NaN,"United Registrar of Systems Polska Sp. z o.o.,...","https://www.google.com/maps?q=50.024140,15.215500",https://hub.iscc-system.org//FileHandler/downl...,https://hub.iscc-system.org//FileHandler/downl...
1,valid.,EU-ISCC-Cert-DE100-09920124,"PT Sinar Sawit Sentosa, Jakarta Pusat, DKI Ja...",TR,NaN,NaN,NaN,2024-03-22,2025-03-21,NaN,"SGS Germany GmbH, Emstek, DE","https://www.google.com/maps?q=-6.154992375,106...",https://hub.iscc-system.org//FileHandler/downl...,https://hub.iscc-system.org//FileHandler/downl...

In [118]:
df['Status']

0          valid.
1          valid.
2          valid.
3          valid.
4          valid.
           ...
55705    expired.
55706    expired.
55707    expired.
55708    expired.
55709    expired.
Name: Status, Length: 55710, dtype: object

In [119]:
df['Status'].unique()

array(['valid.',
       'This certificate will be valid shortly. See starting date!',
       'expired.',
       'The validity of the certificate is currently suspended according to ISCC System Document 102, chapter 10.2.1.',
       'withdrawn.', 'terminated.'], dtype=object)

In [120]:
df.columns

Index(['Status', 'Certificate ID', 'Certificate Holder', 'Scope',
       'Raw Material', 'Add-Ons', 'Products', 'Valid From', 'Valid Until',
       'Suspended', 'Issuing CB', 'Map', 'Certificate', 'Audit Report'],
      dtype='object')

In [121]:
df['Certificate Holder']

0        Bioenergo - Komplex, s.r.o.,  Kolín, Czech Rep...
1        PT Sinar Sawit Sentosa,  Jakarta Pusat, DKI Ja...
2           Kazmunaygas Trading AG,  Paradiso, Switzerland
3                Nippon Dyneema Co,  Tsuruga, Fukui, Japan
4            RECYOIL ENERGY, S.L.,  Vitoria (Álava), Spain
                               ...
55705                       ADM Mainz GmbH, Mainz, GERMANY
55706                              Bioro NV, Gent, Belgium
55707                            Cargill NV, Gent, BELGIUM
55708          ADM Szamotuly Sp. z o.o., Szamotuly, POLAND
55709            Bioeton Deutschland GmbH, Kyritz, Germany
Name: Certificate Holder, Length: 55710, dtype: object

In [122]:
df['Certificate Holder'][8974]

'Vendys & V s.r.o., Česká Lípa, Czech Republic'

In [123]:
df['Certificate Holder'][46000].split(",")[-1]

' Austria'

In [124]:
len(df['Certificate Holder'])

55710

In [125]:
df.columns

Index(['Status', 'Certificate ID', 'Certificate Holder', 'Scope',
       'Raw Material', 'Add-Ons', 'Products', 'Valid From', 'Valid Until',
       'Suspended', 'Issuing CB', 'Map', 'Certificate', 'Audit Report'],
      dtype='object')

In [126]:
df['Company_Name'] = [''] * len(df['Certificate Holder'])
df['country'] = [''] * len(df['Certificate Holder'])
df['city'] = [''] * len(df['Certificate Holder'])

In [127]:


df['Company_Name'] = df['Certificate Holder'].apply(lambda x: x.split(",")[0].strip() if isinstance(x, str) and len(x.split(",")) >= 1 else np.nan)



df['country'] = df['Certificate Holder'].apply(lambda x: x.split(",")[-1].strip() if isinstance(x, str) and len(x.split(",")) >= 2 else np.nan)

df['country'] = df['country'].apply(lambda x: x.title() if isinstance(x, str) else x)

df['city'] = df['Certificate Holder'].apply(lambda x: x.split(",")[-2].strip() if isinstance(x, str) and len(x.split(",")) >= 2 else np.nan)

df['city'] = df['city'].apply(lambda x: x.title() if isinstance(x, str) else x)

In [128]:
df[df['city'].isna()]

,Status,Certificate ID,Certificate Holder,Scope,Raw Material,Add-Ons,Products,Valid From,Valid Until,Suspended,Issuing CB,Map,Certificate,Audit Report,Company_Name,country,city
8306,valid.,EU-ISCC-Cert-DE105-86754603,NaN,"FG, CR, OM",Palm,NaN,...,2023-06-30,2024-06-29,NaN,CUCG,"https://www.google.com/maps?q=1673.87, -895657.15",https://certificates.iscc-system.org/cert-pdf...,https://certificates.iscc-system.org/cert-audi...,NaN,NaN,NaN
8307,valid.,ISCC-PLUS-Cert-DE105-87654603,NaN,"FG, CR, OM",NaN,NaN,NaN,2023-06-30,2024-06-29,NaN,CUCG,"https://www.google.com/maps?q=1673.87, -895657.15",https://certificates.iscc-system.org/cert-pdf...,https://certificates.iscc-system.org/cert-audi...,NaN,NaN,NaN
13597,expired.,EU-ISCC-Cert-PL219-86576704,NaN,CP,UCO,NaN,NaN,2022-12-06,2023-12-05,NaN,CUP,https://www.google.com/maps?q=38.9724888888888...,https://certificates.iscc-system.org/cert-pdf...,https://certificates.iscc-system.org/cert-audi...,NaN,NaN,NaN
15062,expired.,EU-ISCC-Cert-ES216-20227096,NaN,FG,"Barley, Corn, Rape ...",NaN,NaN,2022-10-11,2023-10-10,NaN,CGN,"https://www.google.com/maps?q=46.183415, 18.95...",https://certificates.iscc-system.org/cert-pdf...,https://certificates.iscc-system.org/cert-audi...,NaN,NaN,NaN
17371,expired.,EU-ISCC-Cert-PL219-86635204,NaN,COP,"AF 3, PFAO",NaN,NaN,2022-07-06,2023-07-05,NaN,CUP,"https://www.google.com/maps?q=40.2376, -3.839",https://certificates.iscc-system.org/cert-pdf...,https://certificates.iscc-system.org/cert-audi...,NaN,NaN,NaN
17372,expired.,ISCC-PLUS-Cert-PL219-86635205,NaN,COP,NaN,NaN,NaN,2022-07-06,2023-07-05,NaN,CUP,"https://www.google.com/maps?q=42.1968, 2.5425",https://certificates.iscc-system.org/cert-pdf...,https://certificates.iscc-system.org/cert-audi...,NaN,NaN,NaN
17547,expired.,EU-ISCC-Cert-DE105-87654602,NaN,"FG, CR, OM",Palm,NaN,...,2022-06-30,2023-06-29,NaN,CUCG,"https://www.google.com/maps?q=1673.87, -895657.15",https://certificates.iscc-system.org/cert-pdf...,https://certificates.iscc-system.org/cert-audi...,NaN,NaN,NaN
17549,expired.,ISCC-PLUS-Cert-DE105-87654602,NaN,"FG, CR, OM",Palm,NaN,...,2022-06-30,2023-06-29,NaN,CUCG,"https://www.google.com/maps?q=1673.87, -895657.15",https://certificates.iscc-system.org/cert-pdf...,https://certificates.iscc-system.org/cert-audi...,NaN,NaN,NaN
18403,expired.,EU-ISCC-Cert-PL214-01130422,NaN,"FA, FG, TRS","Corn, Rape/canola ...",NaN,NaN,2022-05-24,2023-05-23,NaN,BV PL,"https://www.google.com/maps?q=47.023974, 18.63...",https://certificates.iscc-system.org/cert-pdf...,https://certificates.iscc-system.org/cert-audi...,NaN,NaN,NaN
21513,expired.,EU-ISCC-Cert-PL219-86576703,NaN,CP,UCO,NaN,NaN,2021-12-06,2022-12-05,NaN,CU,https://www.google.com/maps?q=38.9724888888888...,https://certificates.iscc-system.org/cert-pdf...,https://certificates.iscc-system.org/cert-audi...,NaN,NaN,NaN
24446,expired.,ISCC-PLUS-Cert-DE105-87654601,NaN,"FG, CR, OM",Palm,NaN,...,2021-06-30,2022-06-29,NaN,CUCG,"https://www.google.com/maps?q=16.895, -89.56663",https://certificates.iscc-system.org/cert-pdf...,https://certificates.iscc-system.org/cert-audi...,NaN,NaN,NaN
25128,expired.,EU-ISCC-Cert-PL214-01130421,NaN,"FA, FG, TRS","Corn, Rape/canola ...",NaN,NaN,2021-05-24,2022-05-23,NaN,BV PL,"https://www.google.com/maps?q=47.023974, 18.63...",https://certificates.iscc-system.org/cert-pdf...,https://certificates.iscc-system.org/cert-audi...,NaN,NaN,NaN
31434,expired.,ISCC-PLUS-Cert-PL214-84751219,Vynova Group,OT,"CTO, Mixed Plastic ...",NaN,NaN,2020-01-23,2021-01-22,NaN,BV PL,"https://www.google.com/maps?q=51.061692, 5.09384",https://certificates.iscc-system.org/cert-pdf...,https://certificates.iscc-system.org/cert-audi...,Vynova Group,NaN,NaN

In [129]:

df['latitude'] = [''] * len(df['Map'])
df['longitude'] = [''] * len(df['Map'])

In [130]:
df['latitude'] = df['Map'].str.extract(r'(\d+\.\d+),(\s*-\d+\.\d+|\s*\d+\.\d+)')[0]
df['longitude'] = df['Map'].str.extract(r'(\d+\.\d+),(\s*-\d+\.\d+|\s*\d+\.\d+)')[1]

# Convert latitude and longitude to float type
df['latitude'] = df['latitude'].astype(float)
df['longitude'] = df['longitude'].astype(float)

# Display the DataFrame
print(df)

         Status                 Certificate ID  \
0        valid.    EU-ISCC-Cert-PL230-01473001
1        valid.    EU-ISCC-Cert-DE100-09920124
2        valid.    EU-ISCC-Cert-RO210-24177194
3        valid.  ISCC-PLUS-Cert-DE105-88327303
4        valid.    EU-ISCC-Cert-PL219-86368006
...         ...                            ...
55705  expired.    DE-B-BLE-BM-10-100-20100068
55706  expired.    DE-B-BLE-BM-10-100-20100031
55707  expired.    DE-B-BLE-BM-10-100-20100030
55708  expired.    DE-B-BLE-BM-10-100-20100048
55709  expired.    DE-B-BLE-BM-10-103-10049001

                                      Certificate Holder        Scope  \
0      Bioenergo - Komplex, s.r.o.,  Kolín, Czech Rep...  FG, TRS, PU
1      PT Sinar Sawit Sentosa,  Jakarta Pusat, DKI Ja...           TR
2         Kazmunaygas Trading AG,  Paradiso, Switzerland           TR
3              Nippon Dyneema Co,  Tsuruga, Fukui, Japan           PU
4          RECYOIL ENERGY, S.L.,  Vitoria (Álava), Spain       CP, TR
...                                                  ...          ...
55705                     ADM Mainz GmbH, Mainz, GERMANY   OM, RE, BP
55706                            Bioro NV, Gent, Belgium           BP
55707                          Cargill NV, Gent, BELGIUM       OM, RE
55708        ADM Szamotuly Sp. z o.o., Szamotuly, POLAND       OM, RE
55709          Bioeton Deutschland GmbH, Kyritz, Germany       OM, BP

                                         Raw Material Add-Ons  \
0                                   Rapeseed / canola     NaN
1                                                 NaN     NaN
2                                                 NaN     NaN
3                                                 NaN     NaN
4      Used cooking oil (UCO) entirely of veg. origin     NaN
...                                               ...     ...
55705                                             NaN     NaN
55706                                             NaN     NaN
55707                                             NaN     NaN
55708                                             NaN     NaN
55709                                             NaN     NaN

                        Products  Valid From Valid Until Suspended  \
0                      Crude oil  2024-03-22  2025-03-21       NaN
1                            NaN  2024-03-22  2025-03-21       NaN
2                            NaN  2024-03-22  2025-03-21       NaN
3      Fabrics / fibres / scrims  2024-03-22  2025-03-21       NaN
4                            NaN  2024-03-22  2025-03-21       NaN
...                          ...         ...         ...       ...
55705                        NaN  2010-11-01  2011-05-22       NaN
55706                        NaN  2010-09-30  2011-05-10       NaN
55707                        NaN  2010-09-30  2011-05-08       NaN
55708                        NaN  2010-10-19  2011-05-08       NaN
55709                        NaN  2010-05-03  2011-05-02       NaN

                                              Issuing CB  \
0      United Registrar of Systems Polska Sp. z o.o.,...
1                           SGS Germany GmbH, Emstek, DE
2                             CertRom SRL, Bucuresti, RO
3      Control Union Certifications Germany GmbH, Ber...
4      Control Union Poland Sp. z o.o., Zielona Gora, PL
...                                                  ...
55705                                                SGS
55706                                                SGS
55707                                                SGS
55708                                                SGS
55709                                                GCE

                                                     Map  \
0      https://www.google.com/maps?q=50.024140,15.215500
1      https://www.google.com/maps?q=-6.154992375,106...
2       https://www.google.com/maps?q=45.992808,8.946135
3      https://www.google.com/maps?q=35.6394397711796...
4      https://www.google.com/maps?q=42.869444,-2.642653
...                                                  ...
55705                                                NaN
55706   https://www.google.com/maps?q=51.13889, 3.785691
55707                                                NaN
55708  https://www.google.com/maps?q=52.5973583333333...
55709                                                NaN

                                             Certificate  \
0      https://hub.iscc-system.org//FileHandler/downl...
1      https://hub.iscc-system.org//FileHandler/downl...
2      https://hub.iscc-system.org//FileHandler/downl...
3      https://hub.iscc-system.org//FileHandler/downl...
4      https://hub.iscc-system.org//FileHandler/downl...
...                                                  ...
55705                                                NaN
55706                                                NaN
55707                                                NaN
55708                                                NaN
55709                                                NaN

                                            Audit Report  \
0      https://hub.iscc-system.org//FileHandler/downl...
1      https://hub.iscc-system.org//FileHandler/downl...
2      https://hub.iscc-system.org//FileHandler/downl...
3      https://hub.iscc-system.org//FileHandler/downl...
4      https://hub.iscc-system.org//FileHandler/downl...
...                                                  ...
55705                                                NaN
55706                                                NaN
55707                                                NaN
55708                                                NaN
55709                                                NaN

                   Company_Name         country             city   latitude  \
0           Bioenergo - Komplex  Czech Republic            Kolín  50.024140
1        PT Sinar Sawit Sentosa       Indonesia      Dki Jakarta   6.154992
2        Kazmunaygas Trading AG     Switzerland         Paradiso  45.992808
3             Nippon Dyneema Co           Japan            Fukui  35.639440
4                RECYOIL ENERGY           Spain  Vitoria (Álava)  42.869444
...                         ...             ...              ...        ...
55705            ADM Mainz GmbH         Germany            Mainz        NaN
55706                  Bioro NV         Belgium             Gent  51.138890
55707                Cargill NV         Belgium             Gent        NaN
55708  ADM Szamotuly Sp. z o.o.          Poland        Szamotuly  52.597358
55709  Bioeton Deutschland GmbH         Germany           Kyritz        NaN

        longitude
0       15.215500
1      106.844740
2        8.946135
3      136.066217
4       -2.642653
...           ...
55705         NaN
55706    3.785691
55707         NaN
55708   16.591819
55709         NaN

[55710 rows x 19 columns]

In [132]:
df['country'][8307]="Guatemala"
df['city'][8307]="Sayaxche"
df['Company_Name'][8307]="Agropecuaria Nuevo San Carlos, S.A."

C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\2769475482.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['country'][8307]="Guatemala"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\2769475482.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['country'][8307]="Guatemala"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\2769475482.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['city'][8307]="Sayaxche"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\2769475482.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'][8307]="Sayaxche"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\2769475482.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Company_Name'][8307]="Agropecuaria Nuevo San Carlos, S.A."
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\2769475482.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company_Name'][8307]="Agropecuaria Nuevo San Carlos, S.A."

In [163]:
len(df[df['Company_Name'].isna()])

2

In [170]:
df[df['Company_Name'].isna()].head(2)

Empty DataFrame
Columns: [Status, Certificate ID, Certificate Holder, Scope, Raw Material, Add-Ons, Products, Valid From, Valid Until, Suspended, Issuing CB, Map, Certificate, Audit Report, Company_Name, country, city, latitude, longitude]
Index: []

In [168]:
df['Certificate'][17371]

' https://certificates.iscc-system.org/cert-pdf/EU-ISCC-Cert-PL219-86635204.pdf'

In [169]:
df['country'][17371]="SPAIN" 
df['city'][17371]="SARVAL BIO-INDUSTRIES SLU"
df['Company_Name'][17371]="K.I.P. Kft."

C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\4133035654.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['country'][17371]="SPAIN"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\4133035654.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['country'][17371]="SPAIN"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\4133035654.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['city'][17371]="SARVAL BIO-INDUSTRIES SLU"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\4133035654.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'][17371]="SARVAL BIO-INDUSTRIES SLU"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\4133035654.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Company_Name'][17371]="K.I.P. Kft."
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\4133035654.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company_Name'][17371]="K.I.P. Kft."

In [165]:
df['country'][25128]="Hungary" #17547,18403
df['city'][25128]="Sárosd"
df['Company_Name'][25128]="K.I.P. Kft."

C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\505105902.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['country'][25128]="Hungary" #17547,18403
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\505105902.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['country'][25128]="Hungary" #17547,18403
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\505105902.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['city'][25128]="Sárosd"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\505105902.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'][25128]="Sárosd"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\505105902.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Company_Name'][25128]="K.I.P. Kft."
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\505105902.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company_Name'][25128]="K.I.P. Kft."

In [161]:
df['country'][24446]="Guatemala" #17547,17549
df['city'][24446]="Sayaxché"
df['Company_Name'][24446]="AGROPECUARIA NUEVO SAN CARLOS S.A. AGROCARSA"

C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1518616834.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['country'][24446]="Guatemala" #17547,17549
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1518616834.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['country'][24446]="Guatemala" #17547,17549
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1518616834.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['city'][24446]="Sayaxché"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1518616834.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'][24446]="Sayaxché"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1518616834.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Company_Name'][24446]="AGROPECUARIA NUEVO SAN CARLOS S.A. AGROCARSA"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1518616834.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company_Name'][24446]="AGROPECUARIA NUEVO SAN CARLOS S.A. AGROCARSA"

In [135]:
df['country'][15062]="Hungary"
df['city'][15062]="Baja"
df['Company_Name'][15062]="PANNÓNIA-TERMÉNY Kft"

C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1299011677.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['country'][15062]="Hungary"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1299011677.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['country'][15062]="Hungary"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1299011677.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['city'][15062]="Baja"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1299011677.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'][15062]="Baja"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1299011677.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Company_Name'][15062]="PANNÓNIA-TERMÉNY Kft"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1299011677.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company_Name'][15062]="PANNÓNIA-TERMÉNY Kft"

In [158]:
df['country'][21513]="Spain" #13597
df['city'][21513]="OSSA DE MONTIEL"
df['Company_Name'][21513]="FULGENCIO GARCÍA MORA"

C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1682657841.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['country'][21513]="Spain" #13597
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1682657841.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['country'][21513]="Spain" #13597
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1682657841.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['city'][21513]="OSSA DE MONTIEL"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1682657841.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'][21513]="OSSA DE MONTIEL"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1682657841.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Company_Name'][21513]="FULGENCIO GARCÍA MORA"
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\1682657841.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Company_Name'][21513]="FULGENCIO GARCÍA MORA"

In [171]:
df.head()

,Status,Certificate ID,Certificate Holder,Scope,Raw Material,Add-Ons,Products,Valid From,Valid Until,Suspended,Issuing CB,Map,Certificate,Audit Report,Company_Name,country,city,latitude,longitude
0,valid.,EU-ISCC-Cert-PL230-01473001,"Bioenergo - Komplex, s.r.o., Kolín, Czech Rep...","FG, TRS, PU",Rapeseed / canola,NaN,Crude oil,2024-03-22,2025-03-21,NaN,"United Registrar of Systems Polska Sp. z o.o.,...","https://www.google.com/maps?q=50.024140,15.215500",https://hub.iscc-system.org//FileHandler/downl...,https://hub.iscc-system.org//FileHandler/downl...,Bioenergo - Komplex,Czech Republic,Kolín,50.024140,15.215500
1,valid.,EU-ISCC-Cert-DE100-09920124,"PT Sinar Sawit Sentosa, Jakarta Pusat, DKI Ja...",TR,NaN,NaN,NaN,2024-03-22,2025-03-21,NaN,"SGS Germany GmbH, Emstek, DE","https://www.google.com/maps?q=-6.154992375,106...",https://hub.iscc-system.org//FileHandler/downl...,https://hub.iscc-system.org//FileHandler/downl...,PT Sinar Sawit Sentosa,Indonesia,Dki Jakarta,6.154992,106.844740
2,valid.,EU-ISCC-Cert-RO210-24177194,"Kazmunaygas Trading AG, Paradiso, Switzerland",TR,NaN,NaN,NaN,2024-03-22,2025-03-21,NaN,"CertRom SRL, Bucuresti, RO","https://www.google.com/maps?q=45.992808,8.946135",https://hub.iscc-system.org//FileHandler/downl...,https://hub.iscc-system.org//FileHandler/downl...,Kazmunaygas Trading AG,Switzerland,Paradiso,45.992808,8.946135
3,valid.,ISCC-PLUS-Cert-DE105-88327303,"Nippon Dyneema Co, Tsuruga, Fukui, Japan",PU,NaN,NaN,Fabrics / fibres / scrims,2024-03-22,2025-03-21,NaN,"Control Union Certifications Germany GmbH, Ber...",https://www.google.com/maps?q=35.6394397711796...,https://hub.iscc-system.org//FileHandler/downl...,https://hub.iscc-system.org//FileHandler/downl...,Nippon Dyneema Co,Japan,Fukui,35.639440,136.066217
4,valid.,EU-ISCC-Cert-PL219-86368006,"RECYOIL ENERGY, S.L., Vitoria (Álava), Spain","CP, TR",Used cooking oil (UCO) entirely of veg. origin,NaN,NaN,2024-03-22,2025-03-21,NaN,"Control Union Poland Sp. z o.o., Zielona Gora, PL","https://www.google.com/maps?q=42.869444,-2.642653",https://hub.iscc-system.org//FileHandler/downl...,https://hub.iscc-system.org//FileHandler/downl...,RECYOIL ENERGY,Spain,Vitoria (Álava),42.869444,-2.642653

In [172]:
df.to_csv("ALL_Clean_DB.csv",index=False)

In [173]:
df=pd.read_csv('clean_csv_195.csv')

In [175]:
df['Emails']

0        {'CB_email': set(), 'Department_email': {'m.si...
1        {'CB_email': {'sustainability.emstek@sgs.com'}...
2        {'CB_email': {'carbon@certrom.ro', 'director@c...
3        {'CB_email': {'berlin@controlunion.com'}, 'Dep...
4        {'CB_email': {'polska@controlunion.com'}, 'Dep...
                               ...
55705                                                  NaN
55706                                                  NaN
55707                                                  NaN
55708                                                  NaN
55709                                                  NaN
Name: Emails, Length: 55710, dtype: object

In [ ]:

df['latitude'] = [''] * len(df['Map'])
df['longitude'] = [''] * len(df['Map'])

In [178]:
import pandas as pd
import numpy as np

# Assuming your DataFrame is named df

# Define a function to extract CB_email and Department_email
def extract_emails(value):
    if isinstance(value, dict):
        cb_emails = value.get('CB_email', set())
        dept_emails = value.get('Department_email', set())
        return cb_emails, dept_emails
    else:
        return set(), set()

# Apply the function to create the 'CB_email' and 'Department_email' columns
df[['CB_email', 'Department_email']] = df['Emails'].apply(lambda x: pd.Series(extract_emails(x)))

# Display the DataFrame with the new columns
print(df)

                             Countries         Phone Numbers  \
0                   {'Czech Republic'}                 set()
1             {'Germany', 'Indonesia'}    {'+62 2165703998'}
2          {'Switzerland', 'Colombia'}  {'+40723291402\n29'}
3      {'Japan', 'Germany', 'germany'}                 set()
4                  {'Spain', 'Poland'}                 set()
...                                ...                   ...
55705                              NaN                   NaN
55706                              NaN                   NaN
55707                              NaN                   NaN
55708                              NaN                   NaN
55709                              NaN                   NaN

                                                  Emails CB_email  \
0      {'CB_email': set(), 'Department_email': {'m.si...       {}
1      {'CB_email': {'sustainability.emstek@sgs.com'}...       {}
2      {'CB_email': {'carbon@certrom.ro', 'director@c...       {}
3      {'CB_email': {'berlin@controlunion.com'}, 'Dep...       {}
4      {'CB_email': {'polska@controlunion.com'}, 'Dep...       {}
...                                                  ...      ...
55705                                                NaN       {}
55706                                                NaN       {}
55707                                                NaN       {}
55708                                                NaN       {}
55709                                                NaN       {}

      Department_email
0                   {}
1                   {}
2                   {}
3                   {}
4                   {}
...                ...
55705               {}
55706               {}
55707               {}
55708               {}
55709               {}

[55710 rows x 5 columns]

In [183]:
import pandas as pd
import numpy as np
import ast  # Library for literal string parsing

# Assuming your DataFrame is named df

# Define a function to parse the string representation of the dictionary
def parse_emails(value):
    if isinstance(value, str):
        # Parse the string to a dictionary
        email_dict = ast.literal_eval(value)
        cb_emails = email_dict.get('CB_email', set())
        dept_emails = email_dict.get('Department_email', set())
        return cb_emails, dept_emails
    else:
        return set(), set()

# Apply the function to create the 'CB_email' and 'Department_email' columns
df[['CB_email', 'Department_email']] = df['Emails'].apply(lambda x: pd.Series(parse_emails(x)))

# Display the DataFrame with the new columns
print(df)

                             Countries         Phone Numbers  \
0                   {'Czech Republic'}                 set()
1             {'Germany', 'Indonesia'}    {'+62 2165703998'}
2          {'Switzerland', 'Colombia'}  {'+40723291402\n29'}
3      {'Japan', 'Germany', 'germany'}                 set()
4                  {'Spain', 'Poland'}                 set()
...                                ...                   ...
55705                              NaN                   NaN
55706                              NaN                   NaN
55707                              NaN                   NaN
55708                              NaN                   NaN
55709                              NaN                   NaN

                                                  Emails  \
0      {'CB_email': set(), 'Department_email': {'m.si...
1      {'CB_email': {'sustainability.emstek@sgs.com'}...
2      {'CB_email': {'carbon@certrom.ro', 'director@c...
3      {'CB_email': {'berlin@controlunion.com'}, 'Dep...
4      {'CB_email': {'polska@controlunion.com'}, 'Dep...
...                                                  ...
55705                                                NaN
55706                                                NaN
55707                                                NaN
55708                                                NaN
55709                                                NaN

                                       CB_email  \
0                                            {}
1               {sustainability.emstek@sgs.com}
2      {carbon@certrom.ro, director@certrom.ro}
3                     {berlin@controlunion.com}
4                     {polska@controlunion.com}
...                                         ...
55705                                        {}
55706                                        {}
55707                                        {}
55708                                        {}
55709                                        {}

                          Department_email
0        {m.simunkova@bioenergokomplex.cz}
1      {irfan.ferdian@julongindonesia.com}
2         {Cristina.Catana@kmgtrading.com}
3               {shigeki_tanaka@toyobo.jp}
4                {oiercordon@rafrinor.com}
...                                    ...
55705                                   {}
55706                                   {}
55707                                   {}
55708                                   {}
55709                                   {}

[55710 rows x 5 columns]

In [188]:
df=df.drop(columns=["Emails","Countries"])

In [189]:
df.head(5)

,Phone Numbers,CB_email,Department_email
0,set(),{},{m.simunkova@bioenergokomplex.cz}
1,{'+62 2165703998'},{sustainability.emstek@sgs.com},{irfan.ferdian@julongindonesia.com}
2,{'+40723291402\n29'},"{carbon@certrom.ro, director@certrom.ro}",{Cristina.Catana@kmgtrading.com}
3,set(),{berlin@controlunion.com},{shigeki_tanaka@toyobo.jp}
4,set(),{polska@controlunion.com},{oiercordon@rafrinor.com}

In [191]:
df['Phone Numbers'].head(15)

0                    set()
1       {'+62 2165703998'}
2     {'+40723291402\n29'}
3                    set()
4                    set()
5                    set()
6                    set()
7                    set()
8      {'+45 40 44 50 42'}
9      {'+45 40 44 50 42'}
10                   set()
11      {'+62 2165703998'}
12    {'+40723291402\n29'}
13                   set()
14                   set()
Name: Phone Numbers, dtype: object

In [194]:
# Function to remove newline characters
import re
def remove_newline(phone_numbers):
    if isinstance(phone_numbers, str):
        return re.sub(r'\n', '', phone_numbers)
    else:
        return phone_numbers

# Apply the function to remove newline characters
df['Phone Numbers'] = df['Phone Numbers'].apply(remove_newline)

In [203]:
df=df.drop(columns=["CB_email"])

In [204]:
df[0:196].tail(15)

             Phone Numbers                   Department_email
181  {'+390131241601\n28'}  {Elisa.Romanello@smurfitkappa.it}
182    {'+45 21 41 14 34'}  {Dan.Christensen@adapa-group.com}
183      {'+46 36 430 33'}   {andreas.grennvall@haboplast.se}
184                  set()                                 {}
185                  set()                                 {}
186                  set()                                 {}
187                  set()                                 {}
188                  set()                                 {}
189                  set()                                 {}
190                  set()                 {522606780@qq.com}
191                  set()             {lesastoiko@gmail.com}
192                  set()      {green.agrofarm.md@gmail.com}
193                  set()                                 {}
194                  set()                                 {}
195                  set()        {anna.vilanova@gcrgroup.es}

In [207]:
full_df=pd.read_csv('source\ALL_Clean_DB.csv')

<>:1: SyntaxWarning: invalid escape sequence '\A'
<>:1: SyntaxWarning: invalid escape sequence '\A'
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\3002638426.py:1: SyntaxWarning: invalid escape sequence '\A'
  full_df=pd.read_csv('source\ALL_Clean_DB.csv')
C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\3002638426.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  full_df=pd.read_csv('source\ALL_Clean_DB.csv')

In [210]:
full_df=full_df[0:196]

In [214]:
full_df['emails']=df['Department_email']

C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\458819212.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_df['emails']=df['Department_email']

In [215]:
full_df['Phone Numbers']=df['Phone Numbers']

C:\Users\faiza\AppData\Local\Temp\ipykernel_8576\217381204.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_df['Phone Numbers']=df['Phone Numbers']

In [218]:
full_df.columns

Index(['Status', 'Certificate ID', 'Certificate Holder', 'Scope',
       'Raw Material', 'Add-Ons', 'Products', 'Valid From', 'Valid Until',
       'Suspended', 'Issuing CB', 'Map', 'Certificate', 'Audit Report',
       'Company_Name', 'country', 'city', 'latitude', 'longitude', 'emails',
       'Phone Numbers'],
      dtype='object')

In [219]:
full_df=full_df.drop(columns=['Status', 'Certificate ID', 'Certificate Holder', 'Scope',
       'Raw Material', 'Add-Ons', 'Products', 'Valid From', 'Valid Until',
       'Suspended', 'Issuing CB', 'Map', 'Certificate', 'Audit Report'])

full_df

,Company_Name,country,city,latitude,longitude,emails,Phone Numbers
0,Bioenergo - Komplex,Czech Republic,Kolín,50.024140,15.215500,{m.simunkova@bioenergokomplex.cz},set()
1,PT Sinar Sawit Sentosa,Indonesia,Dki Jakarta,6.154992,106.844740,{irfan.ferdian@julongindonesia.com},{'+62 2165703998'}
2,Kazmunaygas Trading AG,Switzerland,Paradiso,45.992808,8.946135,{Cristina.Catana@kmgtrading.com},{'+40723291402\n29'}
3,Nippon Dyneema Co,Japan,Fukui,35.639440,136.066217,{shigeki_tanaka@toyobo.jp},set()
4,RECYOIL ENERGY,Spain,Vitoria (Álava),42.869444,-2.642653,{oiercordon@rafrinor.com},set()
...,...,...,...,...,...,...,...
191,"LLC""OILFRITURE""",Ukraine,Lviv,NaN,NaN,{lesastoiko@gmail.com},set()
192,„GREEN AGRO FARM” SRL,Moldova,Chisinau,46.564708,28.253786,{green.agrofarm.md@gmail.com},set()
193,Inabata Malaysia Sdn Bhd,Malaysia,Kuala Lumpur,3.153710,101.707010,{},set()
194,Qingdao Huizheng New Energy Technology Co.,China,Shandong Province,36.226670,120.148640,{},set()
195,Gestora Catalana de Residuos S.L.U,Spain,La Bisbal Del Penedès,41.270798,1.505415,{anna.vilanova@gcrgroup.es},set()

In [220]:
full_df.to_csv('Contact_details.csv')

In [211]:
df

              Phone Numbers                     Department_email
0                     set()    {m.simunkova@bioenergokomplex.cz}
1        {'+62 2165703998'}  {irfan.ferdian@julongindonesia.com}
2      {'+40723291402\n29'}     {Cristina.Catana@kmgtrading.com}
3                     set()           {shigeki_tanaka@toyobo.jp}
4                     set()            {oiercordon@rafrinor.com}
...                     ...                                  ...
55705                   NaN                                   {}
55706                   NaN                                   {}
55707                   NaN                                   {}
55708                   NaN                                   {}
55709                   NaN                                   {}

[55710 rows x 2 columns]

In [206]:
df[0:196].to_csv("Contact_details.csv", index=False)

In [182]:
import ast
row = "{'CB_email': set(), 'Department_email': {'m.simunkova@bioenergokomplex.cz'}}"

# Parse the string to a dictionary
email_dict = ast.literal_eval(row)

# Extract CB_email and Department_email
cb_emails = email_dict.get('CB_email', set())
dept_emails = email_dict.get('Department_email', set())

print("CB_email:", cb_emails)
print("Department_email:", dept_emails)

CB_email: set()
Department_email: {'m.simunkova@bioenergokomplex.cz'}

In [181]:
df['Emails'][0]

"{'CB_email': set(), 'Department_email': {'m.simunkova@bioenergokomplex.cz'}}"